apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: service-b
data:
  RABBITMQ_HOST: "{{ .Values.rabbitmq.host }}"
  RABBITMQ_PORT: "{{ .Values.rabbitmq.port }}"
  RABBITMQ_USER: "{{ .Values.rabbitmq.user }}"
  RABBITMQ_QUEUE: "{{ .Values.rabbitmq.queue }}"
  GCS_BUCKET_NAME: "{{ .Values.gcs.bucket }}"