apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service-b
  labels:
    app: service-b
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - name: service-b
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: RABBITMQ_HOST
            - name: RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: RABBITMQ_PORT
            - name: RABBITMQ_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: RABBITMQ_USER
            - name: RABBITMQ_QUEUE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: RABBITMQ_QUEUE
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASSWORD
            - name: GCS_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: GCS_BUCKET_NAME
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/app/credentials/credentials.json"
          volumeMounts:
            - name: gcp-credentials
              mountPath: "/app/credentials"
              readOnly: true
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials-secret