apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service-b
  labels:
    app: service-b
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: service-b